# .github/workflows/runOnGitHub.yml
# GitHub Actions documentation
# => https://docs.github.com/en/actions
name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:
jobs:
  gradle:
    strategy:
      matrix:
        #os:  [windows-latest, macos-latest, ubuntu-latest]
        os:  [ubuntu-latest, macos-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: |
            build.gradle.kts
            gradle.properties
            settings.gradle.kts

      - name: install dependencies ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt install libcurl4-openssl-dev

      # Execute Gradle commands in GitHub Actions workflows
      # => https://github.com/marketplace/actions/gradle-command
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: ./gradlew runOnGithubAction
      - id: artifact
        name: Add build scan to the artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildscan-assemble
          path: 'buildscan.log'
